$ANSIBLE_VAULT;1.1;AES256
65333339393966396137343337383932646238393861353838366430333834386137313135336638
6630313164383864306665623330316665383530323731300a316438653364616531666464643235
34626137393266393461303631363464616366633061356434646264373465633836653638303763
6436653961636362630a353435653430656263386536653261306331383165373664376433616162
33646231313266383763346233386331306236353161366639653239376231653733303136373062
61356138376330666539616165633639316531613330323535396636353861343637666461346634
30346564613039356337623836346238316630653163396132646239336230346165346265363061
34613365393035613135356132333632356236636134336435323530303461316465393736353036
30313636363431383035616666666462363739306536636430323236626465316163393234616338
30393731313232343837383066336262333261316134663964633564393962326130636537613865
34313762346662623737393634646430393964353763306637653936353935306162646530616632
39356263613632353063653534623933333265613233653831323534646238366163383536396134
65643831396263333165643334386437623739336266313837323063313462663432
